### ISSUE TITLE
[BUG] Settings do not save when player disconnects

### ISSUE THREAD

**Issue by GodDirtman** [limbo56/PlayerSettings#46]
**Describe the bug**

When players leave the server and join back, they don't have the effects from the settings they enabled. In settings' GUI the Enabled/Disabled state is being saved, but with no impact on the player.

**To Reproduce**

1. Turn on any setting in GUI, e.g. `speed`.
2. Leave the server and join again
3. When you join back, you do not have the effect applied, but the GUI displays the set state (Enabled/Disabled).

**Expected behavior**

Settings state should save.

**Server version**

`This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-298 (MC: 1.19.2)`

**Additional context**

Thanks for solving the previous issue I reported. Keep up the good work!

**Comment by limbo56** [comment]
Hello @GodDirtman

Thanks again for helping iron out issues with the plugin. I've tried to reproduce this with the latest release, and it seems to behave fine on my end. Could you verify the configuration of your speed/jump settings has the new section called `triggers`? 

This new property is replacing the `executeOnJoin` property. It is a list of events/actions under which the setting should apply its effects. In the case of settings that use a potion effect (like speed and jump), you need to re-apply those potion effects when a player joins and respawns. Settings like the visibility, vanish and fly settings also need to apply their effects when a player joins.

Either way, here is an example of what your default speed and jump settings should look like:
```yaml
speed-setting:
  enabled: true
  default: 0
  max: 5
  triggers:
  - join # Applies the speed effect on join
  - respawn # Applies the speed effect on respawn

jump-setting:
  enabled: true
  default: 0
  max: 10
  triggers:
  - join # Applies the jump effect on join
  - respawn # Applies the jump effect on respawn
```

To avoid any further conflicts with the default settings, I recommend you generate a new `settings.yml` file and transfer over any changes. Sorry for the confusion, and I hope this helps.
